KINGS_LANDING = "King's Landing"
WINTERFELL = "Winterfell"
THE_WALL = "The Wall"
STORMS_END = "Storm's End"
RIVERRUN = "River Run"
CASTERLYROCK = "CasterlyRock"
SUNSPEAR = "Sunspear"

LOCATIONS = [KINGS_LANDING,WINTERFELL,THE_WALL,STORMS_END,RIVERRUN ,CASTERLYROCK ,SUNSPEAR]